apiVersion: v1
kind: Service
metadata:
  name: visionary-api
  namespace: visionary-analytics
spec:
  type: ClusterIP
  selector:
    app: visionary-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
