apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-data
  namespace: visionary-analytics
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
