name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore VisionaryAnalytics.sln
      - name: Build
        run: dotnet build VisionaryAnalytics.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test VisionaryAnalytics.sln --configuration Release --no-build
